# Generated by Django 4.0.4 on 2022-06-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
