# Generated by Django 4.0.4 on 2022-06-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_agency_id_agency_agency_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='agency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='max_passengers',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='min_passengers',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
