# Generated by Django 4.0.4 on 2022-06-07 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_trip_agency_alter_trip_max_passengers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='max_passengers',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='min_passengers',
        ),
    ]
