# Generated by Django 4.0.4 on 2022-06-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_trip_max_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='max_passengers',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='trip',
            name='min_passengers',
            field=models.IntegerField(default=2),
        ),
    ]
